### ISSUE TITLE
Woocommerce 3.0.5 int32 issue

### ISSUE THREAD

**Issue by shawnvdb** [XiaoFaye/WooCommerce.NET#123]
I upgraded to 3.0.5 and the problem is back again.

Exception thrown: 'System.Runtime.Serialization.SerializationException' in System.Runtime.Serialization.dll

Additional information: There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.Order, WooCommerceNET, Version=0.5.6.0, Culture=neutral, PublicKeyToken=null]]. The value 'total' cannot be parsed as the type 'Int32'.

I there anything I can change in the code that will fix this problem?

**Comment by mbeauchamp7** [comment]
As of right now the `total` property looks like this 
```
/// <summary>
/// Grand total. 
/// read-only
/// </summary>
[DataMember(EmitDefaultValue = false)]
public decimal? total { get; set; }
```

but if you look at the doc, they send it as a string and I know @XiaoFaye has been doing this "workaround" to correctly parse the value.

```
/// <summary>
/// Grand total. 
/// read-only
/// </summary>
[DataMember(EmitDefaultValue = false)]
public decimal? total { get; set; }
```

**Comment by shawnvdb** [comment]
Thanks, I tried your fork and I may have misunderstood you above, but I get the same problem.

**Comment by goguvi** [comment]
Could you paste the JSON that gives the error?

**Comment by shawnvdb** [comment]
I have trimmed the json string to the following: 

"[{\"id\":9582,\"discount_total\":\"0.00\",\"discount_tax\":\"0.00\",\"shipping_total\":\"148.00\",\"shipping_tax\":\"0.00\",\"cart_tax\":\"0.00\",\"total\":\"3153.86\",\"total_tax\":\"0.00\",\"subtotal\":\"1942.40\",\"subtotal_tax\":\"0.00\",\"total\":\"1942.40\",\"total_tax\":\"0.00\",\"taxes\":[],\"subtotal\":\"1063.46\",\"subtotal_tax\":\"0.00\",\"total\":\"1063.46\",\"total_tax\":\"0.00\",\"taxes\":[],\"meta\":[]}],\"tax_lines\":[],\"total\":\"148.00\",\"total_tax\":\"0.00\",\"taxes\":[{\"id\":\"total\",\"total\":[]}]}],\"fee_lines\":[],\"coupon_lines\":[],\"refunds\":[]

The full stack trace is as follows:

System.Runtime.Serialization.SerializationException occurred
  HResult=-2146233076
  Message=There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.Order, WooCommerceNET, Version=0.5.6.0, Culture=neutral, PublicKeyToken=null]]. The value 'total' cannot be parsed as the type 'Int32'.
  Source=System.Runtime.Serialization
  StackTrace:
       at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
       at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
       at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
       at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString) in C:\Dev\WooCommerce.NET-master\WooCommerce.NET-master\RestAPI.cs:line 269
  InnerException: 
       HResult=-2146232000
       LineNumber=0
       LinePosition=0
       Message=The value 'total' cannot be parsed as the type 'Int32'.
       Source=System.Runtime.Serialization
       StackTrace:
            at System.Runtime.Serialization.Json.XmlJsonReader.ParseInt(String value, NumberStyles style)
            at System.Runtime.Serialization.Json.XmlJsonReader.ReadContentAsInt()
            at System.Xml.XmlDictionaryReader.ReadElementContentAsInt()
            at System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsInt()
            at ReadTaxItemFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
            at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
            at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
            at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
            at ReadArrayOfTaxItemFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
            at System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
            at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
            at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
            at ReadShippingLineFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
            at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
            at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
            at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
            at ReadArrayOfShippingLineFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
            at System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
            at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
            at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
            at ReadOrderFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
            at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
            at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
            at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
            at ReadArrayOfOrderFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
            at System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
            at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
            at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
            at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
            at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
            at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
       InnerException: 
            HResult=-2146233033
            Message=Input string was not in a correct format.
            Source=mscorlib
            StackTrace:
                 at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
                 at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
                 at System.Runtime.Serialization.Json.XmlJsonReader.ParseInt(String value, NumberStyles style)
            InnerException:

**Comment by goguvi** [comment]
I have not tested yet 3.0.5 but in 3.0.3 the error was not the total property, but another property with 'total' as the value.  In 3.0.3 the error was that shipping_lines/taxes was returned wrong (see https://github.com/XiaoFaye/WooCommerce.NET/issues/107#issuecomment-295159349).

**Comment by shawnvdb** [comment]
It has always been the total value when I have had this problem. You can see that in my previous issue as well.

**Comment by mbeauchamp7** [comment]
@shawnvdb sorry I was not clear about my statement, I only fixed the products yet, I'll get the orders soon though. I can see in the Json you posted that the Id of the tax is "total" though `"taxes":[{"id":"total","total":[]}]` and probably a problem with WooCommerce in the first place.

**Comment by goguvi** [comment]
I have updated a test site to 3.0.5, it seems that the orders works correctly for me. I have no clue what is happening at your website.

**Comment by shawnvdb** [comment]
Could it be that I do not have taxes enabled?

**Comment by shawnvdb** [comment]
@mbeauchamp7 You wouldn't by any change have an idea when you could have the orders section done? :D

**Comment by mbeauchamp7** [comment]
@shawnvdb I'm not currently working on this but I'll let you know when I will have done it. I'm curious to know if @XiaoFaye is actually planning to update this or not, so we don't update the same things..

**Comment by XiaoFaye** [comment]
Hi @mbeauchamp7 , @shawnvdb , new wrapper is on the way for the new version of API.

**Comment by XiaoFaye** [comment]
Hi @mbeauchamp7 , @shawnvdb , source code of version 0.7.0 has been committed, however, I need to do more testing to release the new version in Nuget.

**Comment by shawnvdb** [comment]
Going to test it now. Will let you know of any issues.

**Comment by goguvi** [comment]
There's an error in WooCommerce 3.0.7. that causes this exception.
See woocommerce/woocommerce#15124 and solution https://github.com/woocommerce/woocommerce/commit/56a3b31e68653afbcac7edffcf25641f110e2647 .
