### ISSUE TITLE
Serialization error when on production server

### ISSUE THREAD

**Issue by sasjacobs** [XiaoFaye/WooCommerce.NET#179]
Wordpress version 4.8, WooCommerceNET.0.7.1, .NET 4.5.1

The code works fine on my local server and I'm able to import products successfully. Thanks!

Once I port to my site host's server, I'm getting a serialization error. This occurs on my own API and I am able to decorate my classes with [Serializable] to fix.

Is there a fix for this issue other than downloading source code and marking classes as serializable?

The error message from the server is:

Unable to serialize the session state. In 'StateServer' and 'SQLServer' mode, ASP.NET will serialize the session state objects, and as a result non-serializable objects or MarshalByRef objects are not permitted. The same restriction applies if similar serialization is done by the custom session state store in 'Custom' mode.
System.Web.HttpException (0x80004005): Unable to serialize the session state. In 'StateServer' and 'SQLServer' mode, ASP.NET will serialize the session state objects, and as a result non-serializable objects or MarshalByRef objects are not permitted. The same restriction applies if similar serialization is done by the custom session state store in 'Custom' mode. ---> System.Runtime.Serialization.SerializationException: Type 'WooCommerceNET.WooCommerce.v2.Product' in Assembly 'WooCommerceNET, Version=0.7.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(WriteObjectInfo objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Web.Util.AltSerialization.WriteValueToStream(Object value, BinaryWriter writer)
   at System.Web.Util.AltSerialization.WriteValueToStream(Object value, BinaryWriter writer)
   at System.Web.SessionState.SessionStateItemCollection.WriteValueToStreamWithAssert(Object value, BinaryWriter writer)
   at System.Web.SessionState.SessionStateItemCollection.Serialize(BinaryWriter writer)
   at System.Web.SessionState.SessionStateUtility.Serialize(SessionStateStoreData item, Stream stream)
   at System.Web.SessionState.SessionStateUtility.SerializeStoreData(SessionStateStoreData item, Int32 initialStreamSize, Byte[]& buf, Int32& length, Boolean compressionEnabled)
   at System.Web.SessionState.OutOfProcSessionStateStore.SetAndReleaseItemExclusive(HttpContext context, String id, SessionStateStoreData item, Object lockId, Boolean newItem)
   at System.Web.SessionState.SessionStateModule.OnReleaseState(Object source, EventArgs eventArgs)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by XiaoFaye** [comment]
Are you sending the objects via session state?

**Comment by sasjacobs** [comment]
No. I'm trying to store them in Session State and retrieve them. My webhost uses a StateServer.

**Comment by XiaoFaye** [comment]
Is it possible for you to serialize the object to json string and store it in Session State, then retrieve it and deserialize back to the object?

**Comment by sasjacobs** [comment]
That's my work around at the moment. Just wondered if there was any way to mark the classes as serializable but I think that might not be possible if it's in a PCL.

**Comment by XiaoFaye** [comment]
@sasjacobs  try to create your own classes inherit from the original ones in PCL and put [Serializable] on it. it should work.

**Comment by XiaoFaye** [comment]
@sasjacobs  Any feedback on this?

**Comment by sasjacobs** [comment]
It's a bit more difficult than your suggestion because I am using a swagger.json file and generating the rest client automatically using AutoRest using a PowerShell command. Our database layer is accessed from an API which we consume in our front end.

I would need to modify the PowerShell script to add the Serializable attribute during client creation time, something which is a bit beyond me at the moment both in terms of skill set and time.

Thanks for the suggestion though.
