### ISSUE TITLE
Get Error 500 : Internal Server Error with latest Woocommerce version and Woocommerce.NET 0.7.2 

### ISSUE THREAD

**Issue by trungdh** [XiaoFaye/WooCommerce.NET#198]
Hello Mr. Xiao Faye
I've just updated WooCommerce system to latest version, and I'm using WooCommerce.NET 0.7.2 version.
When I call to any APIs on WooCommerce system (https://mysite.com/wc-api/v3/customers endpoint, https://mysite.com/wc-api/v3/customers/count endpoint or https://mysite.com/wc-api/v3/customers/email/test@gmail.com endpoint).  I'm used WooCommerceNET.WooCommerce.Legacy.WCObject for v3 APIs version
I get error code 500 : Internal Server Error with details exception which fired by SendHttpClientRequest method of RestAPI object at line 149 : 

> WebResponse wr = await httpWebRequest.GetResponseAsync().ConfigureAwait(false);

The details of Exception as below: 

>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at WooCommerceNET.Base.Extension.<>c__DisplayClass2_0.<GetResponseAsync>b__0(IAsyncResult iar) in D:\Working\WooCommerce.NET\WooCommerce.NET-master\Base\Extension.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WooCommerceNET.RestAPI.<SendHttpClientRequest>d__20`1.MoveNext() in D:\Working\WooCommerce.NET\WooCommerce.NET-master\RestAPI.cs:line 149
    The remote server returned an error: (500) Internal Server Error.

Do you have any idea for my problem, Mr. Xiao Faye ? 
I am very grateful for any help from you !

Thank you !

**Comment by XiaoFaye** [comment]
This error is returned by the web server, please send the actual error message.

**Comment by trungdh** [comment]
Sorry for my limitations. But how can I get the actual error message, Mr. Xiao Faye ? 
That's all message which I get from StackTrace when I'm debug program. 
Could you please show me ? Mr. Xiao

Many thanks !

**Comment by XiaoFaye** [comment]
Please check your web server logs
