### ISSUE TITLE
UpdateOrder error

### ISSUE THREAD

**Issue by enzocontrerasc** [XiaoFaye/WooCommerce.NET#222]
Dear I hope someone can help me I am trying to update the status of an order but it does not work for me, it gives me the same error when updating product info. review the API permissions and they are Read / Write.
Perform the PostProduct() product creation example  and it works without problem.

--google Traslate. 

- Wordpress 4.8.3, WooCommerce 3.2.2.2 and WooCommerce.NET 0.7.2

RestAPI rest = new RestAPI("http://hofmannonline.azurewebsites.net/wp-json/wc/v1", "ck_26b0b1525895daaaa34dae87750e804fb72ca736", "cs_21474f2e6480a7f0bef384a5b975f3708f65c51b", false);
            WCObject wc = new WCObject(rest);

            string result = await wc.UpdateOrder(424, new Order { status = "cancelled" }); **Error

Error:
System.Net.WebException occurred
  HResult=0x80131509
  Message=The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used.
  Source=WooCommerceNET
  StackTrace:
   at WooCommerceNET.RestAPI.<SendHttpClientRequest>d__20`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WooCommerceNET.WooCommerce.v1.WCObject`14.<UpdateOrder>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WooComerce.Form1.<Form1_Load>d__1.MoveNext() in c:\users\econtreras\documents\visual studio 2017\Projects\WooComerce\WooComerce\Form1.cs:line 38

**Comment by XiaoFaye** [comment]
Can you try Postman and see how it goes?

**Comment by enzocontrerasc** [comment]
already review it make the same change and the error is the same

![image](https://user-images.githubusercontent.com/22843535/32293762-f2131c72-bf22-11e7-9599-eb3503d050b1.png)

**Comment by enzocontrerasc** [comment]
Solve- cambie de Hosting y funciono
