### ISSUE TITLE
Error getting products and variations

### ISSUE THREAD

**Issue by blueman2000** [XiaoFaye/WooCommerce.NET#234]
WooCommerce Version 3.2.6
Wordpress 4.9.1WC .NET 0.7.2.0
.NET 4.5.2

I have two different bug. When I get all products, I got this error:

System.Runtime.Serialization.SerializationException occurred
  HResult=0x8013150C
  Message=Fehler beim Deserialisieren des Objekts "vom Typ System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.ProductCategory, WooCommerceNET, Version=0.7.2.0, Culture=neutral, PublicKeyToken=null]]". Es wurde das Endelement "display" aus Namespace "" erwartet. Gefunden wurde "Element "item" aus Namespace """.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString)
   at WooCommerceNET.Base.WCItem`1.<GetAll>d__10.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FakturaServer.WooCommerce.ObjMngWooCommerce.<GetProductCategories>d__12.MoveNext() in D:\ProjekteCS\Lynx\WaWiServer\WooCommerce\ObjMngWooCommerce.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FakturaServer.WooCommerce.ObjMngWooCommerce.<GetWooCommerceData>d__9.MoveNext() in D:\ProjekteCS\Lynx\WaWiServer\WooCommerce\ObjMngWooCommerce.cs:line 69

Inner Exception 1:
XmlException: Es wurde das Endelement "display" aus Namespace "" erwartet. Gefunden wurde "Element "item" aus Namespace """.

System.Runtime.Serialization.SerializationException occurred
  HResult=0x8013150C
  Message=Fehler beim Deserialisieren des Objekts "vom Typ System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.ProductCategory, WooCommerceNET, Version=0.7.2.0, Culture=neutral, PublicKeyToken=null]]". Es wurde das Endelement "display" aus Namespace "" erwartet. Gefunden wurde "Element "item" aus Namespace """.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString)
   at WooCommerceNET.Base.WCItem`1.<GetAll>d__10.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FakturaServer.WooCommerce.ObjMngWooCommerce.<GetProductCategories>d__12.MoveNext() in D:\ProjekteCS\Lynx\WaWiServer\WooCommerce\ObjMngWooCommerce.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FakturaServer.WooCommerce.ObjMngWooCommerce.<GetWooCommerceData>d__9.MoveNext() in D:\ProjekteCS\Lynx\WaWiServer\WooCommerce\ObjMngWooCommerce.cs:line 69

Inner Exception 1:
XmlException: Es wurde das Endelement "display" aus Namespace "" erwartet. Gefunden wurde "Element "item" aus Namespace """.

I changed the program and read all products by id, and I found one product which made the problem.
I thought the problem was a ' in the product name. I removed it and the problem still occured, then I added it again. The problem disappered - I can now read all products without problems.

But now when I read variations, I have an other issue / bug. Same again with all vairations, so I read step by step:

		Message	"Fehler beim Deserialisieren des Objekts \"vom Typ WooCommerceNET.WooCommerce.v2.Variation\". Die Eingabezeichenfolge hat das falsche Format."	string

-		InnerException	{System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   bei WooCommerceNET.Base.JsonObject.OnDeserialized(StreamingContext ctx)
   bei ReadVariationFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)}	System.Exception {System.FormatException}

I did not edit the variation yet in woocommerce, just to make sure to fix the bug. Can you give me a hint?

**Comment by XiaoFaye** [comment]
It looks like the website doesn't return a correct json string, you need to debug into the source code and have a look.
