### ISSUE TITLE
Refunds - The value '' cannot be parsed as the type 'Int32'

### ISSUE THREAD

**Issue by EugeneTheDeveloper** [XiaoFaye/WooCommerce.NET#269]
WordPress 4.9.5
WooCommerce 3.2.6
WooCommerce.NET 0.7.4

When calling WCObject.Order.Refunds.GetAll(orderId), it throws the exception "The value '' cannot be parsed as the type 'Int32'". 

If I call the endpoint from Postman, the returned JSON has a blank value for tax_class:
[{"id": 119, ... , "line_items": [ { "id": 14,  ..., "tax_class": "", ... } ], ... } ]

Looking at the library source, I think the exception is due to line in OrderRefund.cs:
public int tax_class { get; set; }
If it was string instead (as it is in all the other classes), I'm guessing this exception wouldn't happen.
This is probably also a mistake in the WooCommerce API docs, which list tax_class as an integer for refund line items, but as a string for everything else.

More error details: 
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.OrderRefund, WooCommerce.NET, Version=0.7.4.0, Culture=neutral, PublicKeyToken=null]]. The value '' cannot be parsed as the type 'Int32'. ---> System.Xml.XmlException: The value '' cannot be parsed as the type 'Int32'. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Runtime.Serialization.Json.XmlJsonReader.ParseInt(String value, NumberStyles style)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.Json.XmlJsonReader.ParseInt(String value, NumberStyles style)
   at System.Xml.XmlDictionaryReader.ReadElementContentAsInt()
   at ReadOrderRefundItemFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at ...

Would it be possible to fix this?

Thanks!
Eugene

**Comment by XiaoFaye** [comment]
have a look at #78 , try to replace **"tax_class": ""**  with **"tax_class": "0"**  for the whole json string.
