### ISSUE TITLE
SerializationException

### ISSUE THREAD

**Issue by nturini-cascinanet** [XiaoFaye/WooCommerce.NET#456]
Hi i'm trying to download from my cistomer site the complete list of articles and i receive this error

```
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type System.Collections.Generic.List1[[WooCommerceNET.WooCommerce.v3.Product, WooCommerce.NET, Version=0.8.1.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. Input string was not in a correct format. ---> System.FormatException: Input string was not in a correct format.
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
at WooCommerceNET.Base.JsonObject.OnDeserialized(StreamingContext ctx)
at ReadProductFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
at ReadArrayOfProductFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
at System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
--- End of inner exception stack trace ---
at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString)
at WooCommerceNET.Base.WCItem1.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
```

It would seem related to a deserialization of a decimal value but i've no idea about what value

The customer have more than 20.000 articles on his woocommerce site and the error is generated after download of 12.000 of them

I think there is one or a small group of articles with this problem but not knowing what generates it I can't correct it, any ideas?
 

Thanks for the support

**Comment by XiaoFaye** [comment]
Please set RestAPI.Debug to true, you should see the json string that cause this error in the error message.

**Comment by mirco261** [comment]
Hi, I think I have same problem. 
`System.Runtime.Serialization.SerializationException: 'Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''. '`

I have about 15.000 articles. How can I set RestAPI.Debug to true ? 
I see via WP plugin API Log that json file and looks good. You can check it here:
> http://www.mojekralovstvo.sk/wp-content/wcv3products-response-body-293575.json

**Comment by nturini-cascinanet** [comment]
Thank you @XiaoFaye 
i think to find a wrong price in product, this is the json


![image](https://user-images.githubusercontent.com/62327651/80694567-f963f980-8ad4-11ea-8791-fc556075edcb.png)


If you need to check this is the full json file 
`[{"id":13587,"name":"XXXXX","slug":"XXXXX","permalink":"https:\/\/XXXXX\/","date_created":"2019-10-13T22:25:37","date_created_gmt":"2019-10-13T20:25:37","date_modified":"2020-04-29T22:59:48","date_modified_gmt":"2020-04-29T20:59:48","type":"simple","status":"publish","featured":false,"catalog_visibility":"visible","description":"<p>XXXXX <\/p>\n","sku":"XXXXX","price":"-","regular_price":"-","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"price_html":"<span class=\"woocommerce-Price-amount amount\">0,00<span class=\"woocommerce-Price-currencySymbol\">&euro;<\/span><\/span>","on_sale":false,"purchasable":true,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"stock_status":"instock","backorders":"no","backorders_allowed":false,"backordered":false,"sold_individually":false,"weight":"","dimensions":{"length":"","width":"","height":""},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0.00","rating_count":0,"related_ids":[2386,2367,2392,2412,2384],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":171,"name":"XXXXX","slug":"XXXXX"}],"tags":[],"images":[{"id":13556,"date_created":"2019-10-13T21:05:00","date_created_gmt":"2019-10-13T17:05:00","date_modified":"2019-10-13T21:05:00","date_modified_gmt":"2019-10-13T17:05:00","src":"https:\/\/XXXXX","name":"XXXXX","alt":""}],"attributes":[],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"meta_data":[{"id":162998,"key":"easyindexInvalidate","value":"1"}],"_links":{"self":[{"href":"https:\/\/XXXXX"}],"collection":[{"href":"https:\/\/XXXXX"}]}}]`


I immediately notify the customer to set the price, I will inform you if I solve the problem

**Comment by mirco261** [comment]
Thank you for answer, I edit products with "-" in prices... but still same error message.
new json here https://mojekralovstvo.sk/wp-content/wcv3products-response-body-295205.json

thank you

**Comment by XiaoFaye** [comment]
@mirco261 Your error is different, look at the json structure, is different from @nturini-cascinanet

**Comment by mirco261** [comment]
ah ok, I will make new issue... I realy dont know where is a problem... 
thank you

**Comment by nturini-cascinanet** [comment]
The problem semms solved, you can close the issue.

**Comment by mirco261** [comment]
yes it was problems with prices with character "-", but problem with deserialization are still.
It helps to set from 100products per page to 50products per page to get products from WC
