### ISSUE TITLE
Legacy not working 

### ISSUE THREAD

**Issue by alxtr1bal** [XiaoFaye/WooCommerce.NET#54]
For example on GetProduct : 

Error : 
There was an error deserializing the object of type WooCommerceNET.WooCommerce.Legacy.Product. The value 'parent' cannot be parsed as the type 'Boolean'.

InnerException : 
{"The string 'parent' is not a valid Boolean value."}

   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString)
   at WooCommerceNET.WooCommerce.Legacy.WCObject.<GetProduct>d__33.MoveNext()

**Comment by XiaoFaye** [comment]
Hi, unfortunately I'm not maintaining the legacy api anymore. However, any pull requests are welcome.
