### ISSUE TITLE
error on GetSalesReport

### ISSUE THREAD

**Issue by ksuwattana** [XiaoFaye/WooCommerce.NET#596]
WordPress 5.6.2
WooCommerce.NET 0.8.3
WooCommerce 5.0.0

Hi 
I found a problem "Could not convert string to integer: 0.00. Path '[0].total_discount'" during use function getsalesreport, could you please help? How can I do?

my code:
public async Task<List<SalesReport>> GetDataSaleReport()
{
    List<SalesReport> report = new List<SalesReport>();
    string period = "last_month";
    string minDate = "2021-02-04";
    string maxDate = "2021-02-04";
    Dictionary<string, string> periods = new Dictionary<string, string>();
    //periods.Add("period", period);
    periods.Add("date_min", minDate);
    periods.Add("date_max", maxDate);
    report = await wc.Report.GetSalesReport(periods);

    return report;
}

error:
{Newtonsoft.Json.JsonReaderException: Could not convert string to integer: 0.00. Path '[0].total_discount', line 1, position 182.
   at Newtonsoft.Json.JsonReader.ReadInt32String(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   ...

**Comment by firestormza** [comment]
Good day, 
I see there is a problem. I've submitted a pull request to fix it. #595

**Comment by ksuwattana** [comment]
Hi firestormza,
Thank you for your suggestion, I'm trying by follow your code :)
