### ISSUE TITLE
Retrieving orders with coupons fails, without coupons work

### ISSUE THREAD

**Issue by Opdebeke** [XiaoFaye/WooCommerce.NET#638]
**Small description**
Whenever I try to retrieve orders with:

//Get all products
var products = await wc.Product.GetAll();

It fails when there are orders present with a coupon line, it succeeds when there are no orders with coupon lines. 

**Versions**
- Wordpress version: 5.8 
- WooCommerce version: 5.5.2
- WooCommerce.NET version: 0.8.3
- Newtonsoft.Json: 13.0.1

**Exact error message**
Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: {. Path '[0].coupon_lines[0].meta_data[0].display_value', line 1, position 4791.'

**Stacktrace**
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Unexpected character encountered while parsing value: {. Path '[0].coupon_lines[0].meta_data[0].display_value', line 1, position 4791.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Novali_App.MyRestAPI.DeserializeJSon[T](String jsonString) in C:\Users\Leroy\OneDrive\Documenten\Visual Studio Repo\Novali App\Novali App\MyRestAPI.cs:line 24
   at WooCommerceNET.Base.WCItem`1.<GetAll>d__11.MoveNext()

  This exception was originally thrown at this call stack:
    [External Code]
    Novali_App.MyRestAPI.DeserializeJSon<T>(string) in MyRestAPI.cs
    [External Code]

**The exact line it fails on**
![image](https://user-images.githubusercontent.com/88661076/128700332-041cde70-54b6-4de6-aea2-a0cf9c223568.png)

**The name of the coupon code**
RoosNovali10 (10% discount) (it could not be that the coupon contains numbers right?)

Official documentation suggest using V2, but I use V3 could this be the problem?
![image](https://user-images.githubusercontent.com/88661076/128700837-5e2249b9-cea3-455a-991c-7b0ba2aa062a.png)

**Comment by Opdebeke** [comment]
I just build a new DLL from souce, problem solved. Any idea when this will be publishes as NuGet package?

**Comment by XiaoFaye** [comment]
@Opdebeke Hopefully later this month.

**Comment by Logic-Bits** [comment]
Hi!

Not only coupons, also it has problems with shipping lines:
`
Unexpected character encountered while parsing value: [. Path '[0].shipping_lines[0].meta_data[1].display_value', 
`
the values is:  "display_value": []

Best

**Comment by dragonblaze5** [comment]
Hi!

Just wondering if there was any update on this issue? We've been facing the same issue but it's when we're getting order details for a specific Id (order data is mapped correctly when no coupon code present, but doesn't parse if a coupon code is applied)  :

`WooCommerceNET.WooCommerce.v3.WCObject wooCommerceContext;`

`//within function that accepts the order Id as parameter`
`var ord = this.wooCommerceContext.Order.Order.Get(Id); // same issue as the OP regarding the display_value attribute, its unable to parse and map the returned object`

Currently on 0.8.3 of the library and 5.7.1 version of WooCommerce.

**Comment by XiaoFaye** [comment]
This has been fixed in version 0.8.4, sorry for the delay.
