### ISSUE TITLE
Any query cannot be parsed if includes German umlaut letter: ï

### ISSUE THREAD

**Issue by lukasan** [XiaoFaye/WooCommerce.NET#649]
The worst kind of error, where it works on some stores, but not on others, while all of them are copies of the same store just for different languages/regions. Differences should be minimal.
Incidentally, the not-working one is in German (https://github.com/XiaoFaye/WooCommerce.NET/issues/638#issuecomment-896087082)
Querying the stores with Postman gives back correct JSON, no abnormalities.

The function I'm using that fails:
```C#
private static async Task<string> WooCommerceApiIsWorkingAsync(WooCommerceStore store)
{
    RestAPI rest = new RestAPI(store.Uri + "/wp-json/wc/v3/", store.apiKey, store.apiSecret);
    WCObject wc = new WCObject(rest);

    var testTag = new ProductTag();
    testTag.description = "This is an automatic test tag. This should be deleted automatically. If you see this, this means something went wrong with the internal system.";
    testTag.name = "Test tag";
    testTag.slug = "test";

    try
    {
        // can perform write?

        var wcTag = await wc.Tag.Add(testTag);
        await wc.Tag.Delete((int)wcTag.id, true);

        return null;
    }
    catch (Exception e) // catches if HTTP 4xx
    {
        return e.Message;
    }
}
```
the `var wcTag = await wc.Tag.Add(testTag);` part works, fails on `await wc.Tag.Delete((int)wcTag.id, true);`. **Writing** data to WooCommerce on such sites does work, while **delete** doesn't.

`jsonString `shows up with all of the JSON correctly too in the override function, breaks on the return Deserialization:
```C#
public override T DeserializeJSon<T>(string jsonString)
{
    if (jsonDeseFilter != null)
        jsonString = jsonDeseFilter.Invoke(jsonString);

    return JsonConvert.DeserializeObject<T>(jsonString);
}
```

### Environment
- WP 5.8.1
- Woo 5.6.0
- Sprache: de_DE_formal
- WooCommerce.NET is from source

### Steps to replicate the issue
1. German site (?)
2. Query anything (tested Tags, Categories, Products)
3. Error

### Details of the error message

`There was an error deserializing the object of type WooCommerceNET.WooCommerce.v3.ProductTag. Encountered unexpected character 'ï'.`
Just noticed from the error while writing this issue, that it's the umlaut letter that throws me the error:
### **ï**

`Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.`

Stack trace:
```   
at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString) in C:\Users\lukas\Downloads\WooCommerce.NET-master\RestAPI.cs:line 454
   at WooCommerceNET.Base.WCItem`1.<Add>d__12.MoveNext() in C:\Users\lukas\Downloads\WooCommerce.NET-master\Base\BaseObject.cs:line 162
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Timberin.Controllers.WooCommerceStoresController.<WooCommerceApiIsWorkingAsync>d__11.MoveNext() in C:\Users\lukas\source\repos\Timberin\Timberin\Controllers\WooCommerceStoresController.cs:line 207
```

:D

**Comment by lukasan** [comment]
Yeah, and after posting I found out that this is well known... https://github.com/XiaoFaye/WooCommerce.NET/issues/216#issuecomment-356502166

**Comment by lukasan** [comment]
Yep, this https://github.com/XiaoFaye/WooCommerce.NET/issues/78#issuecomment-273564975 works. Sorry.
