### ISSUE TITLE
Variations Deserializing Exception

### ISSUE THREAD

**Issue by palmeItGit** [XiaoFaye/WooCommerce.NET#715]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
- WP version 6.0.3 , Woocommerce Version 7.0.0, WooCommerce.NET version 0.8.4

- Steps to replicate the issue
- I am getting the following error while querying for variation.

- Details of the error message if there is any
- There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.Variation, WooCommerce.NET, Version=0.8.4.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. Input string was not in a correct format.
- 
![variations](https://user-images.githubusercontent.com/105352881/197533374-7a61d902-5829-4a53-a06b-5b50104bbe8d.JPG)

**Comment by palmeItGit** [comment]
I found rotten apple. This is a plugin. The plugin is ELEX WooCommerce Catalog Mode, Wholesale & Role Based Pricing. I want to send exception detail for support team. How can i do this. thanks a lot.

**Comment by palmeItGit** [comment]
at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString)
   at WooCommerceNET.Base.WCSubItem`1.<GetAll>d__14.MoveNext()
   at WoocommerceDesktopProject.frmProduct.<CheckExistOnWoo>d__17.MoveNext() in D:\source\repos\WoocommerceDesktopProject\WoocommerceDesktopProject\frmProduct.cs:line 180
   at WoocommerceDesktopProject.frmProduct.<btnCheck_Click>d__15.MoveNext() in D:\source\repos\WoocommerceDesktopProject\WoocommerceDesktopProject\frmProduct.cs:line 147

need an urgency solution, please

**Comment by palmeItGit** [comment]
hi again;

I think i found error. Please look end of json last character. How can i solve this:

```
[{"id":4629,"date_created":"2021-10-06T09:09:43","date_created_gmt":"2021-10-06T09:09:43","date_modified":"2021-12-16T14:56:21","date_modified_gmt":"2021-12-16T14:56:21","description":"","permalink":"https:\/\/www.bioron.de\/product\/realline-hpv-screen-set-1\/?attribute_pa_hpv-hcr-screen=str","sku":"VBD8444Set1","price":false,"regular_price":false,"sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":false,"status":"publish","purchasable":false,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"stock_status":"instock","backorders":"no","backorders_allowed":false,"backordered":false,"low_stock_amount":null,"weight":"","dimensions":{"length":"","width":"","height":""},"shipping_class":"","shipping_class_id":0,"image":{"id":4650,"date_created":"2021-10-06T11:14:43","date_created_gmt":"2021-10-06T11:14:43","date_modified":"2021-10-06T11:14:43","date_modified_gmt":"2021-10-06T11:14:43","src":"https:\/\/www.bioron.de\/wp-content\/uploads\/2021\/10\/2021-10_Goldlady_klein.jpg","name":"2021-10_Goldlady_klein","alt":""},"attributes":[{"id":21,"name":"RealLine HPV HCR Screen","option":"Str"}],"menu_order":1,"meta_data":[{"id":27197,"key":"afreg_field_required","value":"off"},{"id":27198,"key":"afreg_field_read_only","value":"off"},{"id":27199,"key":"afreg_field_order_details","value":"off"},{"id":27200,"key":"afreg_field_user_roles","value":""},{"id":27201,"key":"afreg_is_dependable","value":"off"},{"id":27243,"key":"product_role_based_price","value":{"List":{"role_price":"912"},"Discounted":{"role_price":"720"},"Distributor":{"role_price":"528"}}},{"id":27244,"key":"product_role_based_price_List","value":"912"},{"id":27245,"key":"product_role_based_price_Discounted","value":"720"},{"id":27246,"key":"product_role_based_price_Distributor","value":"528"}],"_links":{"self":[{"href":"https:\/\/www.bioron.de\/wp-json\/wc\/v3\/products\/4626\/variations\/4629"}],"collection":[{"href":"https:\/\/www.bioron.de\/wp-json\/wc\/v3\/products\/4626\/variations"}],"up":[{"href":"https:\/\/www.bioron.de\/wp-json\/wc\/v3\/products\/4626"}]}}]'
```
When i removed this character and paste jon valdator everything fine

**Comment by palmeItGit** [comment]
````
There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.Variation, WooCommerce.NET, Version=0.8.4.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. Input string was not in a correct format.

[{"id":4629,"date_created":"2021-10-06T09:09:43","date_created_gmt":"2021-10-06T09:09:43","date_modified":"2021-12-16T14:56:21","date_modified_gmt":"2021-12-16T14:56:21","description":"","permalink":"https:\/\/www.bioron.de\/product\/realline-hpv-screen-set-1\/?attribute_pa_hpv-hcr-screen=str","sku":"VBD8444Set1","price":false,"regular_price":false,"sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":false,"status":"publish","purchasable":false,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"stock_status":"instock","backorders":"no","backorders_allowed":false,"backordered":false,"low_stock_amount":null,"weight":"","dimensions":{"length":"","width":"","height":""},"shipping_class":"","shipping_class_id":0,"image":{"id":4650,"date_created":"2021-10-06T11:14:43","date_created_gmt":"2021-10-06T11:14:43","date_modified":"2021-10-06T11:14:43","date_modified_gmt":"2021-10-06T11:14:43","src":"https:\/\/www.bioron.de\/wp-content\/uploads\/2021\/10\/2021-10_Goldlady_klein.jpg","name":"2021-10_Goldlady_klein","alt":""},"attributes":[{"id":21,"name":"RealLine HPV HCR Screen","option":"Str"}],"menu_order":1,"meta_data":[{"id":27197,"key":"afreg_field_required","value":"off"},{"id":27198,"key":"afreg_field_read_only","value":"off"},{"id":27199,"key":"afreg_field_order_details","value":"off"},{"id":27200,"key":"afreg_field_user_roles","value":""},{"id":27201,"key":"afreg_is_dependable","value":"off"},{"id":27243,"key":"product_role_based_price","value":{"List":{"role_price":"912"},"Discounted":{"role_price":"720"},"Distributor":{"role_price":"528"}}},{"id":27244,"key":"product_role_based_price_List","value":"912"},{"id":27245,"key":"product_role_based_price_Discounted","value":"720"},{"id":27246,"key":"product_role_based_price_Distributor","value":"528"}],"_links":{"self":[{"href":"https:\/\/www.bioron.de\/wp-json\/wc\/v3\/products\/4626\/variations\/4629"}],"collection":[{"href":"https:\/\/www.bioron.de\/wp-json\/wc\/v3\/products\/4626\/variations"}],"up":[{"href":"https:\/\/www.bioron.de\/wp-json\/wc\/v3\/products\/4626"}]}}]
````
This is full error detail. @XiaoFaye please help me! i need as urgency

**Comment by palmeItGit** [comment]
I think i found a problem. as you can see price and regular_price assigned false. when i change their values with 1000 everything ok. but i dont understand, why false? because in wocommerce screen i showed their values as numeric.

hey anyone here?

**Comment by palmeItGit** [comment]
yes, the problem is definitely the price adjustment plugin called Elex. The purpose of this plugin is to show different prices according to user roles. When this plugin is active, the prices of woocommerce are blocked and their values are marked as false. When I deactivate the plugin and run it; I can see all the data.
