### ISSUE TITLE
WooCommerce version 9.0 compatibility

### ISSUE THREAD

**Issue by gocasals** [XiaoFaye/WooCommerce.NET#775]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version 6.5.4, WooCommerce Versión 9.0.0 and WooCommerce.NET version 4.6.1

- Steps to replicate the issue
after updating to woocommerce 9.0 it is not possible to connect

- Details of the error message if there is any

   en WooCommerceNET.RestAPI.<SendHttpClientRequest>d__48`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci n anterior donde se produjo la excepci n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en WooCommerceNET.RestAPI.<GetRestful>d__49.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci n anterior donde se produjo la excepci n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en WooCommerceNET.Base.WCItem`1.<GetAll>d__11.MoveNext()<---

**Comment by XiaoFaye** [comment]
I just tested with Get Orders, seems working fine with WooCommerce 9, could you provide more details?

**Comment by gocasals** [comment]
wc.Product.GetAll(dic).Result

![image](https://github.com/XiaoFaye/WooCommerce.NET/assets/48871662/86ec6383-a1ca-4e1d-adcb-4824a3894f46)

   at WooCommerceNET.RestAPI.<SendHttpClientRequest>d__48`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WooCommerceNET.RestAPI.<GetRestful>d__49.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WooCommerceNET.Base.WCItem`1.<GetAll>d__10.MoveNext()

**Comment by XiaoFaye** [comment]
Working fine for me

![image](https://github.com/XiaoFaye/WooCommerce.NET/assets/6334728/561d652b-2edc-4272-b7a8-5add5714da64)

**Comment by gocasals** [comment]
https://wordpress.org/support/topic/fatal-error-4703/
